### ISSUE TITLE
Suspend/Resume breaks video API <= 23 

### ISSUE THREAD

**Issue by Rachnerd** [NathanaelA/nativescript-exoplayer#16]
Hey,

## Issue
Video breaks after resuming the app at API levels lower than 24.

#### API 19
![API 19](https://media.giphy.com/media/3ohhwrjuMUFKNBkGs0/giphy.gif)

#### API 23
![API 23](https://media.giphy.com/media/l1J9yAnT94GY1dOr6/giphy.gif)

#### API 24 (works)
![API 24](https://media.giphy.com/media/3ohhweGMlaiP6a0rZK/giphy.gif)

## Potential cause
Inside the [Exoplayer demo activity source](https://github.com/google/ExoPlayer/blob/release-v2/demo/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java) we see an explicit check on API level <= 23. It releases the player on suspend and it reinits on resume. Does this conflict with NativeScript or is this an Exoplayer issue?

**Comment by NathanaelA** [comment]
@Rachnerd - Yeah, we actually have a suspend `suspendEvent` /resume `resumeEvent` you can call; you just attach them to the application life cycle resume/suspend events.    Butwe don't have that documented in our documentation...

We should actually tie them into those events ourselves.  So that it is something that is automatically setup.   Thanks for the heads up.   I'll try and get that fix in the next version so that people don't have to manually do this...

**Comment by NathanaelA** [comment]
Should be fixed in 3.3

**Comment by LSmint** [comment]
I have the similar issue when i open new screen in the video player page. After close the new screen, the video player is disappear on the first page.
